directories:
  interim: data/interim
  processed: data/processed
  raw: data/raw
files:
  dataset_name: credit_risk_dataset.csv
  interim:
    X_test: X_test.pkl
    X_train: X_train.pkl
    X_valid: X_valid.pkl
    y_test: y_test.pkl
    y_train: y_train.pkl
    y_valid: y_valid.pkl
path_X_test: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/X_test.pkl
path_X_train: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/X_train.pkl
path_X_valid: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/X_valid.pkl
path_interim_dir: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim
path_processed_dir: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/processed
path_raw_data: data/raw/credit_risk_dataset.csv
path_raw_dir: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/raw
path_y_test: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/y_test.pkl
path_y_train: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/y_train.pkl
path_y_valid: /home/amadeo/Pacmann/MLProcess/Mentoring/AMADEO_MLPROCESS/data/interim/y_valid.pkl
