directories:
  raw: "data/raw"
  interim: "data/interim"
  processed: "data/processed"

files:
  dataset_name: "credit_risk_dataset.csv"
  interim:
    X_train: "X_train.pkl"
    y_train: "y_train.pkl"
    X_valid: "X_valid.pkl"
    y_valid: "y_valid.pkl"
    X_test: "X_test.pkl"
    y_test: "y_test.pkl"